language: scala 

scala:
  - 2.11.8

script: 
  - sbt ++$TRAVIS_SCALA_VERSION test

branches:
  only:
    - scala
    - java
    - master

# Use container-based infrastructure
sudo: false

# These directories are cached to S3 at the end of the build
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/

